name: Backend CI

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: my-project-95-480908
  REGION: us-central1
  REPOSITORY: backend-repo
  IMAGE_NAME: backend-app

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/550659200096/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: gha-deployer-sa@my-project-95-480908.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build \
            -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA} .

      - name: Push Docker image
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}
